name: Sync with terminal-wiki

on:
  schedule:
    # This schedule runs the workflow every hour. Adjust as needed.
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout wiki repository
        uses: actions/checkout@v2
        with:
          repository: charanravi-online/wiki
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Fetch changes from terminal-wiki
        run: |
          git remote add upstream https://github.com/charanravi-online/terminal-wiki.git
          git fetch upstream
          git merge upstream/main --no-edit
          git push origin main

